import io
from io import BytesIO
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image
from reportlab.lib.units import inch
from reportlab.lib import colors
import httpx
import base64

def generate_notes_pdf_bytes(tutorial_title: str, notes: list) -> bytes:
    """
    Generates a PDF from a list of notes and returns it as bytes.
    """
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter,
                            rightMargin=72, leftMargin=72,
                            topMargin=72, bottomMargin=18)
    
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'TitleStyle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#6366f1'),
        spaceAfter=20,
        alignment=1 # Center
    )
    
    note_time_style = ParagraphStyle(
        'NoteTimeStyle',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.HexColor('#6366f1'),
        spaceAfter=4,
        fontName='Helvetica-Bold'
    )
    
    note_text_style = ParagraphStyle(
        'NoteTextStyle',
        parent=styles['Normal'],
        fontSize=12,
        textColor=colors.HexColor('#1f2937'),
        spaceAfter=12,
        leading=16
    )
    
    Story = []
    
    # Title
    Story.append(Paragraph(tutorial_title, title_style))
    Story.append(Spacer(1, 0.2 * inch))
    
    # Notes
    for note in notes:
        timestamp = note.get('timestamp', '0:00')
        note_content = note.get('note_content', '')
        media_urls = note.get('media_urls', [])
        
        # Add Timestamp
        Story.append(Paragraph(f"[{timestamp}]", note_time_style))
        
        # Add Text Content
        if note_content:
            Story.append(Paragraph(note_content.replace('\n', '<br/>'), note_text_style))
            
        # Add Media
        for media_url in media_urls:
            try:
                # Fetch image from URL
                response = httpx.get(media_url, timeout=10.0)
                if response.status_code == 200:
                    img_data = BytesIO(response.content)
                    img = Image(img_data)
                    
                    # Resize image proportionally to fit page width
                    available_width = doc.width
                    img_width = img.drawWidth
                    img_height = img.drawHeight
                    
                    if img_width > available_width:
                        ratio = available_width / img_width
                        img.drawWidth = available_width
                        img.drawHeight = img_height * ratio
                        
                    # Max height check (e.g. 4 inches max)
                    max_height = 4 * inch
                    if img.drawHeight > max_height:
                        ratio = max_height / img.drawHeight
                        img.drawHeight = max_height
                        img.drawWidth = img.drawWidth * ratio
                        
                    Story.append(img)
                    Story.append(Spacer(1, 0.1 * inch))
            except Exception as e:
                print(f"Failed to load image for PDF: {e}")
                
        Story.append(Spacer(1, 0.2 * inch))
        
    if not notes:
        Story.append(Paragraph("No notes available for this tutorial.", note_text_style))
        
    # Footer - Generated By Note Tube
    Story.append(Spacer(1, 0.5 * inch))
    footer_style = ParagraphStyle(
        'FooterStyle',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.HexColor('#9ca3af'),
        alignment=1, # Center
        fontName='Helvetica-Oblique'
    )
    Story.append(Paragraph("Generated By Note Tube", footer_style))
        
    doc.build(Story)
    
    pdf_bytes = buffer.getvalue()
    buffer.close()
    
    return pdf_bytes
